#pragma once

#include <space-shooter/ecs/systems/input_system.hpp>
#include <space-shooter/ecs/systems/movement_system.hpp>
#include <space-shooter/ecs/systems/rendering_system.hpp>
#include <space-shooter/ecs/systems/scene_menu_system.hpp>
#include <space-shooter/ecs/systems/text_blink_system.hpp>
#include <space-shooter/ecs/systems/shooting_system.hpp>
#include <space-shooter/ecs/systems/clock_system.hpp>
#include <space-shooter/ecs/systems/enemy_spawner_system.hpp>
#include <space-shooter/ecs/systems/collision_system.hpp>
#include <space-shooter/ecs/systems/clean_killed_ships_system.hpp>
#include <space-shooter/ecs/systems/scene_level_system.hpp>
#include <space-shooter/ecs/systems/scene_exit_system.hpp>
#include <space-shooter/ecs/systems/health_bar_display_system.hpp>
#include <space-shooter/ecs/systems/timer_system.hpp>
#include <space-shooter/ecs/systems/text_rendering_system.hpp>
#include <space-shooter/ecs/systems/scoring_system.hpp>
#include <space-shooter/ecs/systems/audio_system.hpp>
#include <space-shooter/ecs/systems/music_system.hpp>
#include <space-shooter/ecs/systems/movement_spawner_system.hpp>
#include <space-shooter/ecs/systems/victory_system.hpp>
#include <space-shooter/ecs/systems/scene_victory_system.hpp>